### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by Ac2333** [zkawfanx/Learning-Temporal-Consistency-for-Low-Light-Video-Enhancement-from-Single-Images#11]
Thank you for your wonderful article!  Can you provide training dataset？

**Comment by zkawfanx** [comment]
Thank you for your interest in our work. Since the training dataset was not the contribution of our work, we had no plan to release the training dataset. The optical flow generation pipeline was provided and you can try to produce data for your purpose.
