### ISSUE TITLE
global affine transformation 全局仿射变换

### ISSUE THREAD

**Issue by Ac2333** [zkawfanx/Learning-Temporal-Consistency-for-Low-Light-Video-Enhancement-from-Single-Images#12]
请问下在您的补充材料中 有提到全局仿射变换，请问这个过程是怎么进行的呢？补充材料中的Figure 2. 的Global那一行的图片是如何得到的？ 非常需要您的指点与解答

**Comment by zkawfanx** [comment]
全局仿射变换包括但不限于 平移、旋转、斜切等可以通过仿射矩阵进行变换的操作，均可通过cv2或kornia等实现。

**Comment by Ac2333** [comment]
您发布的predict_optical_flow.py里面进行了全局仿射变换的处理吗？ 还是说需要我自己额外添加全局仿射变换的处理呢？

**Comment by zkawfanx** [comment]
predict_optical_flow.py里只涉及到利用CMP预训练模型生成光流的步骤，生成对应光流后你可以选择单独使用或结合全局仿射变换来进行处理。

**Comment by Ac2333** [comment]
晚上好！我一开始是单独使用的，就只用了CMP预训练模型生成光流之后就用train.py进行训练，最后测试的效果不是很好，周围的环境会很朦胧，我怀疑是没有进行全局仿射变换。请问您是如何将CMP和全局仿射变换相结合的呢？

**Comment by Ac2333** [comment]
能麻烦您在仓库中发布一下将CMP和全局仿射变换相结合的代码吗？那将会是个非常大的帮助和贡献，非常感谢！！

**Comment by zkawfanx** [comment]
> 晚上好！我一开始是单独使用的，就只用了CMP预训练模型生成光流之后就用train.py进行训练，最后测试的效果不是很好，周围的环境会很朦胧，我怀疑是没有进行全局仿射变换。请问您是如何将CMP和全局仿射变换相结合的呢？

检查下你生成的光流结果，可以尝试不同的随机范围。CMP和全局仿射变换按照顺序结合，先对mask生成的区域施加光流变换，再对全图进行平移旋转等全局放射变换即可。

**Comment by Ac2333** [comment]
> > 晚上好！我一开始是单独使用的，就只用了CMP预训练模型生成光流之后就用train.py进行训练，最后测试的效果不是很好，周围的环境会很朦胧，我怀疑是没有进行全局仿射变换。请问您是如何将CMP和全局仿射变换相结合的呢？
> 
> 检查下你生成的光流结果，可以尝试不同的随机范围。CMP和全局仿射变换按照顺序结合，先对mask生成的区域施加光流变换，再对全图进行平移旋转等全局放射变换即可。

好的，我尝试一下，非常感谢！！
