### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by Ac2333** [zkawfanx/Learning-Temporal-Consistency-for-Low-Light-Video-Enhancement-from-Single-Images#14]
下面这2张图是我训练出来的模型得到的最终测试结果，增强后的图片很不自然，很多区域变的很朦胧。我是按照您的论文来处理的训练数据：首先把DAVIS数据集合成低光数据集，然后用detectron2得到掩码，再用得到的掩码进行CMP预测光流。
我唯一缺少的步骤就是没有将CMP预测的光流和全局仿射变换相结合。所以是因为缺少了这个步骤导致最后生成的模型不行吗？您有什么建议或者看法呢
![20230916-163953](https://github.com/zkawfanx/StableLLVE/assets/90593708/5f442c45-8089-4667-9fea-6247137a1895)
![20230916-163958](https://github.com/zkawfanx/StableLLVE/assets/90593708/3b5572c3-653f-48de-93e9-6d2992e1f4ce)

**Comment by zkawfanx** [comment]
你预测的光流可视化结果是什么样的呢，根据你的描述，应该先用DAVIS数据集的原始图片来获得掩码和光流，而不是利用合成的低光数据来预测掩码。

需要注意的是，通过DAVIS合成的低光数据并不能保证你训练出来的模型能够处理好真实图片，因为合成的数据和真实数据存在的domain gap很大，这与是否添加仿射变换可能并没有太大的关系，而且测试结果中物体周围的棋盘状伪影是UNet网络模型自身存在的问题。

建议先将DAVIS数据集划分为训练集与测试集，并用相同的方式合成暗光数据，并保证测试集中暗光参数与训练集存在一定差异，再测试训练的模型效果，以验证你整个流程的问题。

**Comment by zkawfanx** [comment]
你预测的光流可视化结果是什么样的呢，根据你的描述，应该先用DAVIS数据集的原始图片来获得掩码和光流，而不是利用合成的低光数据来预测掩码。

需要注意的是，通过DAVIS合成的低光数据并不能保证你训练出来的模型能够处理好真实图片，因为合成的数据和真实数据存在的domain gap很大，这与是否添加仿射变换可能并没有太大的关系，而且测试结果中物体周围的棋盘状伪影是UNet网络模型自身存在的问题。

建议先将DAVIS数据集划分为训练集与测试集，并用相同的方式合成暗光数据，并保证测试集中暗光参数与训练集存在一定差异，再测试训练的模型效果，以验证你整个流程的问题。

**Comment by Ac2333** [comment]
我的确是先用DAVIS数据集的原始图片来获得掩码和光流的。下面是我的光流结果
![微信图片_20230920155337](https://github.com/zkawfanx/StableLLVE/assets/90593708/ddc824a2-a049-4f32-b9d5-ecc5ad21ab78)
![微信图片_20230920155341](https://github.com/zkawfanx/StableLLVE/assets/90593708/a1a70cbc-1bf3-4892-a58b-65df34515239)
您觉得生成的光流有什么问题吗？

**Comment by zkawfanx** [comment]
看着没什么问题。你可以先直接在你合成的数据集上直接训练U-Net作为基准，不使用光流参与训练，然后再在你展示的图上进行测试，这样就能确定是你合成的暗光数据domain gap太大，还是没有使用全局变换造成的问题。

**Comment by Ac2333** [comment]
> 看着没什么问题。你可以先直接在你合成的数据集上直接训练U-Net作为基准，不使用光流参与训练，然后再在你展示的图上进行测试，这样就能确定是你合成的暗光数据domain gap太大，还是没有使用全局变换造成的问题。

好的！感谢您的指导
