### ISSUE TITLE
图像质量测评

### ISSUE THREAD

**Issue by Ac2333** [zkawfanx/Learning-Temporal-Consistency-for-Low-Light-Video-Enhancement-from-Single-Images#16]
请问论文中的Table1.是在哪个数据集上进行的指标测评？ 您能提供这个测试数据集吗？我想在这个数据集上对我新训练的模型进行测评 
![微信图片_20230921151237](https://github.com/zkawfanx/StableLLVE/assets/90593708/8a604268-be80-4ac0-8a03-aa0f9e281e66)

**Comment by zkawfanx** [comment]
Experimental Setup部分有描述，是DAVIS合成数据集上进行的测评，数据集并不是我们论文的贡献点，我们没有提供测试数据的计划，建议你按照自己的split进行实验即可。

**Comment by Ac2333** [comment]
明白了，谢谢！！

> Experimental Setup部分有描述，是DAVIS合成数据集上进行的测评，数据集并不是我们论文的贡献点，我们没有提供测试数据的计划，建议你按照自己的split进行实验即可。
