### ISSUE TITLE
关于DAVIS数据集生成

### ISSUE THREAD

**Issue by HebeiFast** [zkawfanx/Learning-Temporal-Consistency-for-Low-Light-Video-Enhancement-from-Single-Images#17]
我能问一下你们davis中同一段视频中每张图片转成lowlight的参数是相同的，还是说同一段视频中每张图片转成lowlight的参数都不一样

**Comment by zkawfanx** [comment]
每一段视频不同帧的lowlight采样参数是保持一致的，这样才符合暗光视频的通常设定，即视频拍摄时相机曝光参数保持一致，故亮度参数保持一致，噪声在给定分布中随机采样。

**Comment by HebeiFast** [comment]
好的，十分感谢

**Comment by Ac2333** [comment]
> 每一段视频不同帧的lowlight采样参数是保持一致的，这样才符合暗光视频的通常设定，即视频拍摄时相机曝光参数保持一致，故亮度参数保持一致，噪声在给定分布中随机采样。

意思是使用伽马校正和线性缩放使图像变暗的参数在同一段视频中是要相同的，但是不同的视频使用不同的采样参数？

**Comment by zkawfanx** [comment]
> > 每一段视频不同帧的lowlight采样参数是保持一致的，这样才符合暗光视频的通常设定，即视频拍摄时相机曝光参数保持一致，故亮度参数保持一致，噪声在给定分布中随机采样。
> 
> 意思是使用伽马校正和线性缩放使图像变暗的参数在同一段视频中是要相同的，但是不同的视频使用不同的采样参数？

是的
