### ISSUE TITLE
关于对比实验

### ISSUE THREAD

**Issue by Ac2333** [zkawfanx/Learning-Temporal-Consistency-for-Low-Light-Video-Enhancement-from-Single-Images#18]
你好！我想请教一下 在你论文的对比实验中，是有MBLLEN 和 MBLLVEN 2种结果，但是我在MBLLEN的源码中并没有找到MBLLVEN的模型，请问你的实验里MBLLVEN的结果是怎么测出来的，MBLLVEN的模型在哪里获得呢？
这是MBLLEN的github地址:https://github.com/Lvfeifan/MBLLEN

**Comment by zkawfanx** [comment]
根据其论文Section 4.5中的描述，MBLLVEN由3D卷积实现，所以只需要将MBLLEN中的conv2d替换为conv3d即可，你也可以参考这个repo中的代码[https://github.com/MichaelHYJiang/csci566-Ocean-s-Five/tree/master/state-of-the-art/bmvc18](url)

**Comment by Ac2333** [comment]
> 根据其论文Section 4.5中的描述，MBLLVEN由3D卷积实现，所以只需要将MBLLEN中的conv2d替换为conv3d即可，你也可以参考这个repo中的代码[https://github.com/MichaelHYJiang/csci566-Ocean-s-Five/tree/master/state-of-the-art/bmvc18](url)

明白了，非常感谢！！
